apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjR1YwY201cGEybDBhVzQ2WjJod1gwVkJlRkkxVURkcmRqZGtaMGczU2t0NFVEZHhXR05wYTJKT1NVZG9UekJGTWtwbU1RPT0ifX19
type: kubernetes.io/dockerconfigjson
